---
    root: true
    parser: babel-eslint
    extends:
        - homezen
        - homezen/node
        - homezen/es-next
        - homezen/es-modules
        - homezen/lodash
        - homezen/react
...
