---
    root: true
    env:
        node: true
        es6: true
    parser: babel-eslint
    parserOptions:
        ecmaVersion: 6
        ecmaFeatures:
            impliedStrict: true
            experimentalObjectRestSpread: true
        sourceType: module
    plugins:
        - react
        - lodash
        - lodash-fp
    extends:
        - eslint:recommended
        - plugin:react/recommended
        - plugin:lodash/recommended
    rules:
        lodash/prefer-lodash-method: 2
        lodash/path-style:
            - 2
            - as-needed
        lodash-fp/no-chain: 2
        lodash-fp/no-argumentless-calls: 2
        lodash-fp/no-extraneous-iteratee-args: 2
        lodash-fp/no-single-composition: 2
        lodash-fp/no-submodule-destructuring: 2
        lodash-fp/prefer-flat-map: 2
        array-bracket-spacing: 2
        arrow-parens:
            - 2
            - always
        arrow-spacing: 2
        block-spacing: 2
        brace-style:
            - 2
            - 1tbs
            -   allowSingleLine: true
        comma-dangle:
            - 2
            - always-multiline
        comma-spacing: 2
        comma-style: 2
        computed-property-spacing: 2
        consistent-this:
            - 2
            - self
        curly: 2
        default-case: 2
        dot-notation: 2
        eol-last: 2
        eqeqeq:
            - 2
            - smart
        indent: 2
        jsx-quotes:
            - 2
            - prefer-single
        key-spacing: 2
        keyword-spacing: 2
        linebreak-style: 2
        max-len:
            - 2
            - 100
            - 4
            -   ignoreUrls: true
                ignorePattern: ^import
        max-params:
            - 2
            - 5
        no-alert: 2
        no-const-assign: 2
        no-continue: 2
        no-dupe-class-members: 2
        no-else-return: 2
        no-eq-null: 2
        no-floating-decimal: 2
        no-implicit-coercion:
            - 2
            -   boolean: false
        no-label-var: 2
        no-loop-func: 2
        no-lonely-if: 2
        no-magic-numbers:
            - 2
            -   ignore:
                    - 0
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
        no-multiple-empty-lines:
            - 2
            -   max: 2
                maxEOF: 1
        no-native-reassign: 2
        no-param-reassign:
            - 2
            -   props: true
        no-return-assign: 2
        no-shadow: 2
        no-shadow-restricted-names: 2
        no-trailing-spaces: 2
        no-undef: 2
        no-undefined: 2
        no-unexpected-multiline: 2
        no-unneeded-ternary: 2
        no-unused-vars: 2
        no-use-before-define:
            - 2
            - nofunc
        no-useless-concat: 2
        no-var: 2
        object-curly-spacing: 2
        object-shorthand:
            - 2
            - always
        prefer-const: 2
        prefer-spread: 2
        prefer-template: 2
        quotes:
            - 2
            - single
            - avoid-escape
        quote-props:
            - 2
            - as-needed
        react/display-name:
            - 2
            -   ignoreTranspilerName: false
        react/jsx-closing-bracket-location:
            - 2
            -   selfClosing: after-props
                nonEmpty: tag-aligned
        react/jsx-curly-spacing: 2
        react/jsx-indent: 2
        react/jsx-indent-props: 2
        react/jsx-key: 2
        react/jsx-uses-vars: 2
        react/jsx-uses-react: 2
        react/jsx-no-bind: 2
        react/jsx-no-duplicate-props: 2
        react/jsx-no-literals: 2
        react/jsx-no-undef: 2
        react/jsx-pascal-case: 2
        react/jsx-wrap-multilines: 2
        react/no-danger: 2
        react/no-deprecated: 2
        react/no-did-mount-set-state: 2
        react/no-did-update-set-state: 2
        react/no-direct-mutation-state: 2
        react/no-is-mounted: 2
        react/no-multi-comp: 2
        react/no-set-state: 2
        react/no-unknown-property: 2
        react/prop-types: 2
        react/self-closing-comp: 2
        react/sort-comp: 2
        react/sort-prop-types:
            - 2
            -   callbacksLast: true
                requiredFirst: true
        semi:
            - 2
            - never
        semi-spacing: 2
        space-in-parens: 2
        space-infix-ops:
            - 2
            -   int32Hint: false
        space-unary-ops: 2
        spaced-comment:
            - 2
            - always
            # -   exceptions:
            #     markers:
        strict:
            - 2
            - never
        valid-jsdoc:
            - 2
            - prefer:
                return: returns
        wrap-iife: 2
        yoda:
            - 2
            - never
            -   exceptRange: true
...
